### ISSUE TITLE
Thảo luận về công nghệ sử dụng và file readme.md

### ISSUE THREAD

**Issue by oakprofessor** [SnakeXenzia/SnakeXenzia#1]
Mở đầu dự án, chúng ta sẽ thảo luận về vấn đề sử dụng ngôn ngữ nào (Java, C, Ruby, ... ) và viết file Readme.md thế nào cho phù hợp.
Trước tiên là về ngôn ngữ, t thấy dùng Java khá ok vì nó hiện nay rất phổ biến và đúng với những gì mình đã được học, anh em có đồng ý không ?

**Comment by xvinh** [comment]
tôi đồng ý, tôi thấy game viết bằng java hiện nay cũng rất phổ biến, nó hộ trợ rất tốt cho việc xây dựng game

**Comment by TranGiang0898** [comment]
okie nhé  dùng eclipse mà code

**Comment by nguyenthuanbg** [comment]
có ai code bằng netbean hay cái gì khác không nhỉ. rv xem cái nào tối ưu hơn thì ae mk dùng

**Comment by nguyenthuanbg** [comment]
còn không thì chốt eclipse đi, tại t quen mỗi eclipse thôi

**Comment by TranGiang0898** [comment]
xong rồi nhé  phần này khái quát thêm lịch sử trò chơi và luật đi

**Comment by oakprofessor** [comment]
Oke issue 1 coi như xong nhé.
