### ISSUE TITLE
Tạo level và lưu trữ thông tin người chơi

### ISSUE THREAD

**Issue by oakprofessor** [SnakeXenzia/SnakeXenzia#10]

**Comment by TranGiang0898** [comment]
Phân này hoàn thiện cập nhật game over cm ạ. T thấy chưa ổn lắm

**Comment by xvinh** [comment]
ukm còn phần level cho người chơi nữa

**Comment by oakprofessor** [comment]
Cần tăng tốc độ rắn và nên giới hạn độ dài rắn ko thì đến đầy màn hình auto thua, chết xong reset lại từ đầu.

**Comment by TranGiang0898** [comment]
chơi xong cần lưu lại tên  và level của người choi nữa cm ơi

**Comment by nguyenthuanbg** [comment]
lúc lên lv rắn đc reset chiều dài đòng thời tăng tốc độ di chuyển và số mồi cần ăn để lên lv tiếp theo

**Comment by TranGiang0898** [comment]
phần thông tin người chơi sử dụng đọc ghi tệp đơn giản luôn nha

**Comment by xvinh** [comment]
ak nhớ lúc rắn chết thì cho reset lv, Giang vs Thuận xử lý cái này nhé

**Comment by TranGiang0898** [comment]
rồi okie nhê  tối mai là xong

**Comment by nguyenthuanbg** [comment]
ok ạ

**Comment by TranGiang0898** [comment]
à chúc mừng năm mới ae nhé =.= <3

**Comment by xvinh** [comment]
HAPPY NEW YEAR!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by oakprofessor** [comment]
Happy new year ✌️

**Comment by nguyenthuanbg** [comment]
yep. hPNY cả nhà
