### ISSUE TITLE
Tạo đối tượng sơ khai ban đầu

### ISSUE THREAD

**Issue by oakprofessor** [SnakeXenzia/SnakeXenzia#2]
Issue này tạo 1 đối tượng đơn giản nhé ( giống kiểu điểm, ô ý).
Trước tiên cần tạo đối tượng sơ khai có thể di chuyển, mọi người nghĩ nên làm thế nào nào ?

**Comment by TranGiang0898** [comment]
Phần tạo đối tượng này cũng khá đơn giản thôi. mình chỉ cần biết vẽ một đồ họa đơn giản trên Panel thôi

**Comment by xvinh** [comment]
ok để t làm phần này cho

**Comment by xvinh** [comment]
t nghĩ làm đối tượng di chuyển đơn giản thôi, vòng lặp for mà triển, ez ấy mà để t làm phần này cho,

**Comment by TranGiang0898** [comment]
Thế gian cần những người như bạn. deadline là 1 ngày thôi nhé.

**Comment by xvinh** [comment]
> Thế gian cần những người như bạn. deadline là 1 ngày thôi nhé.

oke Giang :V

**Comment by oakprofessor** [comment]
t thấy phần giới hạn số khung hình trên giây chưa được ổn lắm

**Comment by TranGiang0898** [comment]
phần này  trong hôm nay sẽ xử lý lại ạ

**Comment by nguyenthuanbg** [comment]
sau đó mình cần triển khai đối tượng lên màn hình cụ thể

**Comment by xvinh** [comment]
ok, để t fix lại phần giới hạn  nhanh thôi

**Comment by oakprofessor** [comment]
Phần triển khai đối tượng lên màn hình cụ thể để t làm cho

**Comment by TranGiang0898** [comment]
chú ý thread nha Quang

**Comment by TranGiang0898** [comment]
à Hạn mai quang nhé

**Comment by oakprofessor** [comment]
Oke
