### ISSUE TITLE
Thiết kế luật chơi

### ISSUE THREAD

**Issue by oakprofessor** [SnakeXenzia/SnakeXenzia#5]
Bây giờ anh em nghĩ thiết kế luật chơi xem ra làm sao.
Trước tiên cần phải làm cho con rắn di chuyển lên xuống trái phải trước.

**Comment by nguyenthuanbg** [comment]
nhận cơ mà để nghĩ xem đã

**Comment by TranGiang0898** [comment]
thì cho nó di chuyển bằng bàn phím.  Xử lý sự kiện đầu vào KeyListener

**Comment by nguyenthuanbg** [comment]
ừm m ơi, sau mk thiết kế rắn dài từ ban đầu luôn, hôm trc làm độ dài rắn đúng 1 ô nhỉ

**Comment by TranGiang0898** [comment]
> ừm m ơi, sau mk thiết kế rắn dài từ ban đầu luôn, hôm trc làm độ dài rắn đúng 1 ô nhỉ

thì băn đầu ngắn ăn mồi vào mí dài chứ =.=. Dài luôn từ đầu chơi chết luôn ư

**Comment by oakprofessor** [comment]
Thuân chú ý lúc con rắn đi ra biên nhé

**Comment by nguyenthuanbg** [comment]
ok nhé

**Comment by nguyenthuanbg** [comment]
à thế lúc rắn đâm ra biên thì làm chết luôn hay đi vào từ biên đối diện thế cm

**Comment by xvinh** [comment]
à thế lúc rắn đâm ra biên thì làm chết luôn hay đi vào từ biên đối diện thế cm

**Comment by oakprofessor** [comment]
Đi vào từ biên đối diện nhé, chết luôn thì game chơi khó quá.

**Comment by TranGiang0898** [comment]
à nhắc đến chết thì nó cắn vào thân thì cho nó chết luôn nhé. Game over luôn

**Comment by oakprofessor** [comment]
Đi vào từ game đối diện r màu mè tí như cái đt cục gạch ngày xưa ý

**Comment by xvinh** [comment]
rắn rồi, bây h cồn mồi nữa, chắc cho xuất hiện random thôi nhỉ

**Comment by TranGiang0898** [comment]
> rắn rồi, bây h cồn mồi nữa, chắc cho xuất hiện random thôi nhỉ

okie nhé. Thế thuận làm phần trên xong thì t làm tiếp phần mồi và cập nhật mồi nhé

**Comment by oakprofessor** [comment]
Giang nhớ là mồi biến mất thì ra mồi mới nhé
Cho các bạn 2 ngày nhé.

**Comment by TranGiang0898** [comment]
> Giang nhớ là mồi biến mất thì ra mồi mới nhé
> Cho các bạn 2 ngày nhé.

 Rõ ạ =.=
