### ISSUE TITLE
Thiết kế đồ họa

### ISSUE THREAD

**Issue by oakprofessor** [SnakeXenzia/SnakeXenzia#7]

**Comment by TranGiang0898** [comment]
hây hây mn t nghĩ chúng t lên thay đổi đồ họa cho game đi. Xấu kinh.

**Comment by nguyenthuanbg** [comment]
định thay đổi thế nào m

**Comment by xvinh** [comment]
> hây hây mn t nghĩ chúng t lên thay đổi đồ họa cho game đi. Xấu kinh.

Vẽ các đối tượng hình học bằng hàm thì  đương nhiên nhìn xấu rồi

**Comment by oakprofessor** [comment]
Dùng hình ảnh đi m

**Comment by xvinh** [comment]
ukm, phần này t biết, để t xử lý cho.

**Comment by oakprofessor** [comment]
Để t chọn hình ảnh rồi gửi m nhé. dăm ba cái con sâu con rắn :3

**Comment by TranGiang0898** [comment]
cho chúng m một ngày để dăm ba con sâu con răn đấy=)) nhớ tạo hiệu ứng cho nó sinh động đấy. Animation

**Comment by TranGiang0898** [comment]
cm  tiến độ đến đâu rồi có mắc chỗ nào không???

**Comment by xvinh** [comment]
mới chỉ hoàn thiện được hình ảnh thôi chưa tạo được hiệu ứng m ạ

**Comment by nguyenthuanbg** [comment]
Giang hướng dẫn vinh cái animation cho nó làm

**Comment by oakprofessor** [comment]
cái  phần hiệu ứng này t làm tiếp cho t là đứa chọn hình ảnh mà

**Comment by TranGiang0898** [comment]
đại khái là mình sử  dụng các hình ảnh nhỏ liên tiếp nhau là tạo được hiệu ứng mà.  t xem hình ảnh rồi . vẽ thêm mấy cái hình ảnh dùng liên tiếp cho rắn  nó mở được miệng cho con sâu rung rinh tẹo

**Comment by nguyenthuanbg** [comment]
Trong ngày mai hai cm hoàn thiện vấn đề này nhé

**Comment by TranGiang0898** [comment]
Thiết kế  làm nhanh ae còn chỉnh nữa

**Comment by oakprofessor** [comment]
Oke nhé ✌️

**Comment by xvinh** [comment]
> Trong ngày mai hai cm hoàn thiện vấn đề này nhé

ok boss
