### ISSUE TITLE
Sửa lại giao diện đồ họa

### ISSUE THREAD

**Issue by oakprofessor** [SnakeXenzia/SnakeXenzia#9]

**Comment by TranGiang0898** [comment]
các m ơi t thấy mình cần thay đổi hình ảnh giao diên rắn và mồi đi... Làm lại mẫu khác nhé.

**Comment by nguyenthuanbg** [comment]
lỗi vùng biên hẹp

**Comment by nguyenthuanbg** [comment]
lỗi vùng biên hẹp nên khi đi đường ở gần biên hình ảnh của rắn hiển thị không đầy đủ

**Comment by xvinh** [comment]
> lỗi vùng biên hẹp

Để t mở rộng thêm khung trò chơi và mở biên ra thêm là ổn.
Cái này nhanh thôi

**Comment by xvinh** [comment]
> lỗi vùng biên hẹp nên khi đi đường ở gần biên hình ảnh của rắn hiển thị không đầy đủ

Để t mở rộng thêm khung trò chơi và mở biên ra thêm là ổn.
Cái này nhanh thôi

**Comment by oakprofessor** [comment]
À mà chơi phải cho bắt đầu và tạm dừng chứ
Bổ sung thêm phím tắt thực hiện chức năng này đi

**Comment by TranGiang0898** [comment]
> À mà chơi phải cho bắt đầu và tạm dừng chứ
> Bổ sung thêm phím tắt thực hiện chức năng này đi

Dung phím cách  cho nhanh. ý tưởng này cho quang triển nhé =.= cái này cũng nhanh mà

**Comment by oakprofessor** [comment]
> > À mà chơi phải cho bắt đầu và tạm dừng chứ
> > Bổ sung thêm phím tắt thực hiện chức năng này đi
> 
> Dung phím cách cho nhanh. ý tưởng này cho quang triển nhé =.= cái này cũng nhanh mà

Oke nhé ✌️

**Comment by nguyenthuanbg** [comment]
mai là phải xong nhé chúng m.

**Comment by xvinh** [comment]
ok let's do it
